### ISSUE TITLE
getting 403 error

### ISSUE THREAD

**Issue by Bitti09** [p3lim/screencloud-caddy#2]
caddyfile:

>  root /var/www/screens.example.de/pics
> browse /
>     upload / {
>         to "/var/www/screens.example.de/pics"
>         hmac_keys_in john=c25vdw==
>     }

screensloud  plugin login:
key=john
secret=c25vdw==

getting 
Upload failed!

403 Client Error: Forbidden for url: https://screens.example.de/

do i miss anything ?

**Comment by p3lim** [comment]
The secret input in the settings for ScreenCloud needs to be the (base64) decrypted version of the secret, in `c25vdw==`'s case it's "snow".

I'll update the readme to make this a bit clearer.

**Comment by Bitti09** [comment]
thanks for the tip 
with snow as secret in screenslkoud it works  as it should :)
